site_name: JSON Serialization Benchmarks
repo_name: json-serialization-benchmarking
repo_url: https://github.com/ZacSweers/json-serialization-benchmarking
site_url: https://zacsweers.github.io/json-serialization-benchmarking
site_description: "Misc benchmarks for JSON serialization."
site_author: Zac Sweers
remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Zac Sweers'

theme:
  name: 'material'
  palette:
    primary: 'deep-orange'
    accent: 'white'
  logo:
    icon: 'notes'
  feature:
    tabs: true

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables
